baseURL: https://openinfra-kr.org
languageCode: ko-kr
title: OpenInfra Korea User Group
theme: "openinfrakr"
paginate: 8
enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
defaultContentLanguage: ko
defaultContentLanguageInSubdir: false
params:
  sponsors:
    - name: "NHN Cloud"
      url: "https://company.nhncloud.com/"
      logo: "/images/sponsors/nhn/nhn_cloud.png"

    - name: "NHN Dooray"
      url: "https://dooray.com/main/"
      logo: "/images/sponsors/nhn/dooray.png"

    - name: "OpenSource"
      url: "https://nhn.com/"
      logo: "/images/sponsors/opensource/logo.png"
  colors:
    base_bg: '#ffffff'
    base_bg_2: '#f8fafc'
    base_bg_3: '#000000'
    base_text: '#202020'
    base_text_2: '#4b5563'
    primary_bg: '#000000'
    primary_bg_2: '#424ff8'
    primary_bg_3: '#ed1844'
    primary_text: '#fdfcf9'
    header_text: '#2b3af7'
    logo_text: '#2b3af7'
    base_bg_dark: '#121212'
    base_bg_2_dark: '#1e1e1e'
    base_bg_3_dark: '#232323'
    base_text_dark: '#ffffff'
    base_text_2_dark: '#d7d7d7'
    primary_bg_dark: '#2b3af7'
    primary_bg_2_dark: '#424ff8'
    primary_bg_3_dark: '#702bf7'
    primary_text_dark: '#fdfcf9'
    logo_text_dark: '#ffffff'
    header_text_dark: '#ffffff'
  fonts:
    use_google_fonts: false
    google_fonts: https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Source+Code+Pro&family=Source+Sans+3:wght@300;400;700&display=swap
    use_self_hosted_fonts: true
    logo: Lato
    heading: Lato
    base: '''Source Sans 3'''
    monospace: '''Source Code Pro'''
  logo:
    logo_text: "OpenInfra Korea Group"
    logo_image_desktop: images/logo/logo.svg
    logo_image_mobile: images/logo/logo-mobile.svg
    logo_image_desktop_invert: images/logo/logo-invert.svg
    logo_image_mobile_invert: images/logo/logo-invert-mobile.svg
    logo_image_desktop_height: "85px"
    logo_image_desktop_width: "132px"
    logo_image_mobile_height: "21px"
    logo_image_mobile_width: "34px"
    show_logo_image_on_mobile: true
    show_logo_image_on_desktop: true
    show_logo_text_on_mobile: false
    show_logo_text_on_desktop: false
  header:
    fixed: true
    header_height: 60px
    header_menu_font_size: 18px
  open_graph:
    og_type: website
    og_twitter_card: summary
    og_twitter_site: '@zerostaticio'
    og_twitter_creator: '@zerostaticio'
  dark_mode:
    enable_dark_mode: true
    show_dark_mode_toggle_in_header: false
    show_dark_mode_toggle_in_bottom: true
    show_dark_mode_toggle_in_mobile_menu: true
  cookie_banner:
    enabled: false
    show_manage_cookies_at_bottom: false
  analytics:
    google_analytics_id: ""
    gtm_id: ""
    plausible_data_domain: ""
    umami_data_website_id: ""
    umami_src: ""
  comments:
    commento:
      enabled: true
    disqus:
      shortname: ""
  newsletter:
    mailchimp:
      form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
      form_title: Let's keep in touch
  contact_form:
    use_netlify_form: false
    use_formspree_form: true
    formspree_endpoint: https://formspree.io/f/moqyklqv
    netlify_form_name: contact
  multilingual:
    enable_language_switcher: true
    show_language_switcher_in_header: true
  menu:
    show_dropdown_items_in_mobile_menu: false
    show_social_media_in_mobile_menu: false
  footer:
    enable_footer: true
    footer_title: OpenInfra Korea User Group
    footer_description: OpenInfra Korea User Group is the home of all open infra communities including OpenStack in Korea.
    enable_social_media_links: false
    enable_languages: true
    enable_copyright: false
    enable_menu_footer_primary: true
    enable_menu_footer_secondary: true
    enable_menu_footer_tertiary: false
    footer_primary_menu_title: About
    footer_secondary_menu_title: Get Involved
    # footer_tertiary_menu_title: Support
  bottom:
    enabled: true
    enable_bottom_menu: true
    copyright_text: © 2024 OpenInfra Korea Group All Rights Reserved
    show_rss_icon: false
languages:
  en:
    weight: 0
    languageName: English
    menu:
      main:
        - name: Home
          identifier: home
          url: 
          weight: 1
        - identifier: about-group
          name: About
          weight: 2
        - identifier: about
          parent: about-group
          name: About
          url: about
          weight: 21
        - identifier: community-group
          name: Community
          weight: 4
        - identifier: forum
          parent: community-group
          name: Forum (Korean)
          url: https://forum.openinfra-kr.org
          weight: 41
          params:
            external: true
        - identifier: hall-of-fame-group
          name: Hall of Fame
          weight: 7
        - identifier: hall-of-fame
          parent: hall-of-fame-group
          name: Hall of Fame
          url: hall-of-fame
          weight: 71
      footer_primary:
        - name: About
          url: about
          weight: 1
      footer_secondary:
        - name: Forum
          url: https://forum.openinfra-kr.org
          weight: 1
          params:
            external: true
            button: true
        - name: OpenInfra Korea Event
          url: https://www.openinfradays.kr
          weight: 2
          params:
            external: true
            button: true
      bottom:
        - name: Terms
          url: terms
          weight: 1
        - name: Privacy
          url: privacy
          weight: 2
  ko:
    weight: 0
    languageName: 한국어
    title: 오픈 인프라 한국 사용자 그룹
    params:
      footer:
        enable_footer: true
        footer_title: 오픈 인프라 한국 사용자 모임
        footer_description: 오픈스택(OpenStack)을 포함한 모든 오픈 인프라를 위한 국내 커뮤니티입니다.
        enable_social_media_links: false
        enable_languages: true
        enable_copyright: false
        enable_menu_footer_primary: true
        enable_menu_footer_secondary: true
        enable_menu_footer_tertiary: false
        footer_primary_menu_title: 소개
        footer_secondary_menu_title: 참여하기
        # footer_tertiary_menu_title: Support
    menu:
      main:
        - name: Home
          identifier: home
          url: 
          weight: 1
        - identifier: about-group
          name: 소개
          weight: 2
        - identifier: about
          parent: about-group
          name: 커뮤니티 소개
          url: about
          weight: 21
        - identifier: community-group
          name: Community
          weight: 4
        - identifier: forum
          parent: community-group
          name: Forum
          url: https://forum.openinfra-kr.org
          weight: 41
          params:
            external: true
        - identifier: mailing
          parent: community-group
          name: Mailing
          url: https://lists.openstack.org/mailman3/lists/openstack-ko.lists.openstack.org/
          weight: 41
          params:
            external: true
        - identifier: facebook
          parent: community-group
          name: Facebook
          url: https://www.facebook.com/groups/openstack.kr
          weight: 41
          params:
            external: true
        - identifier: discord
          parent: community-group
          name: Discord
          url: https://discord.gg/vCM6Qj8uKB
          weight: 41
          params:
            external: true
        - identifier: hall-of-fame-group
          name: 명예의 전당
          weight: 7
        - identifier: hall-of-fame
          parent: hall-of-fame-group
          name: 명예의 전당
          url: hall-of-fame
          weight: 71
      footer_primary:
        - name: About
          url: about
          weight: 1
      footer_secondary:
        - name: Forum
          url: https://forum.openinfra-kr.org
          weight: 1
          params:
            external: true
            button: true
        - name: Discord
          url: https://discord.gg/vCM6Qj8uKB
          weight: 2
          params:
            external: true
            button: true
        - name: Facebook
          url: https://www.facebook.com/groups/openstack.kr
          weight: 3
          params:
            external: true
            button: true
        - name: Mailing
          url: https://lists.openstack.org/mailman3/lists/openstack-ko.lists.openstack.org/
          weight: 4
          params:
            external: true
            button: true
      bottom:
        - name: Terms
          url: terms
          weight: 1
        - name: Privacy
          url: privacy
          weight: 2
permalinks:
  posts: blog/:year/:month/:title/
  pages: :slug/
taxonomies:
  tag: tags
  category: categories
  portfolio: portfolio
  author: authors
markup:
  goldmark:
    renderer:
      unsafe: true
