baseURL: https://openinfra-kr.org
languageCode: ko-kr
title: OpenInfra Korea User Group
theme: "openinfrakr"
paginate: 8
enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
params:
  colors:
    base_bg: '#ffffff'
    base_bg_2: '#f8fafc'
    base_bg_3: '#f1f5f9'
    base_text: '#202020'
    base_text_2: '#4b5563'
    primary_bg: '#2b3af7'
    primary_bg_2: '#424ff8'
    primary_bg_3: '#702bf7'
    primary_text: '#fdfcf9'
    header_text: '#2b3af7'
    logo_text: '#2b3af7'
    base_bg_dark: '#121212'
    base_bg_2_dark: '#1e1e1e'
    base_bg_3_dark: '#232323'
    base_text_dark: '#ffffff'
    base_text_2_dark: '#d7d7d7'
    primary_bg_dark: '#2b3af7'
    primary_bg_2_dark: '#424ff8'
    primary_bg_3_dark: '#702bf7'
    primary_text_dark: '#fdfcf9'
    logo_text_dark: '#ffffff'
    header_text_dark: '#ffffff'
  fonts:
    use_google_fonts: false
    google_fonts: https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Source+Code+Pro&family=Source+Sans+3:wght@300;400;700&display=swap
    use_self_hosted_fonts: true
    logo: Lato
    heading: Lato
    base: '''Source Sans 3'''
    monospace: '''Source Code Pro'''
  logo:
    logo_text: "OpenInfra Korea Group"
    logo_image_desktop: images/logo/logo.svg
    logo_image_mobile: images/logo/logo-mobile.svg
    logo_image_desktop_invert: images/logo/logo-invert.svg
    logo_image_mobile_invert: images/logo/logo-invert-mobile.svg
    logo_image_desktop_height: "85px"
    logo_image_desktop_width: "132px"
    logo_image_mobile_height: "21px"
    logo_image_mobile_width: "34px"
    show_logo_image_on_mobile: true
    show_logo_image_on_desktop: true
    show_logo_text_on_mobile: false
    show_logo_text_on_desktop: false
  header:
    fixed: true
    header_height: 60px
    header_menu_font_size: 18px
  open_graph:
    og_type: website
    og_twitter_card: summary
    og_twitter_site: '@zerostaticio'
    og_twitter_creator: '@zerostaticio'
  dark_mode:
    enable_dark_mode: true
    show_dark_mode_toggle_in_header: false
    show_dark_mode_toggle_in_bottom: true
    show_dark_mode_toggle_in_mobile_menu: true
  cookie_banner:
    enabled: false
    show_manage_cookies_at_bottom: false
  analytics:
    google_analytics_id: ""
    gtm_id: ""
    plausible_data_domain: ""
    umami_data_website_id: ""
    umami_src: ""
  comments:
    commento:
      enabled: true
    disqus:
      shortname: ""
  newsletter:
    mailchimp:
      form_action_url: https://zerostatic.us21.list-manage.com/subscribe/post?u=798e19886b83aaab346734382&amp;id=f1c526a772&amp;f_id=0027e3e6f0
      form_title: Let's keep in touch
  contact_form:
    use_netlify_form: false
    use_formspree_form: true
    formspree_endpoint: https://formspree.io/f/moqyklqv
    netlify_form_name: contact
  multilingual:
    enable_language_switcher: true
    show_language_switcher_in_header: true
  menu:
    show_dropdown_items_in_mobile_menu: false
    show_social_media_in_mobile_menu: true
  footer:
    enable_footer: true
    footer_title: OpenInfra Korea Group
    footer_description: OpenInfra Korea Group is home of all open infra community including OpenStack
    enable_social_media_links: true
    enable_languages: true
    enable_copyright: false
    enable_menu_footer_primary: true
    enable_menu_footer_secondary: true
    enable_menu_footer_tertiary: false
    footer_primary_menu_title: About
    footer_secondary_menu_title: Get Involved
    # footer_tertiary_menu_title: Support
  bottom:
    enabled: true
    enable_bottom_menu: true
    copyright_text: © 2024 OpenInfra Korea Group All Rights Reserved
    show_rss_icon: true
languages:
  en:
    weight: 0
    languageName: English
    menu:
      main:
        - name: Home
          identifier: home
          url: /
          weight: 1
        - name: About
          identifier: about
          #url: /about/
          url: /
          pageRef: about
          weight: 2
        # - name: Branding
        #   parent: services
        #   url: /services/branding
        #   params:
        #     icon: images/icons/icons8-color-palette-100.png
        - name: News
          identifier: news
          url: /news/
          pageRef: news
          weight: 3
        - name: Community
          identifier: community
          url: /community/
          pageRef: community
          weight: 4
        - name: Tech
          identifier: tech
          url: /tech/
          pageRef: tech
          weight: 5
        - name: Get Involved
          identifier: get-involved
          url: /get-involved/
          pageRef: get-involved
          weight: 6
        - name: Hall of Fame
          identifier: hall-of-fame
          url: /hall-of-fame/
          pageRef: hall-of-fame
          weight: 7
        - name: Forum
          url: https://forum.openinfra-kr.org
          weight: 10
          params:
            external: true
            button: true
      footer_primary:
        - name: Team
          url: /team/
          pageRef: team
          weight: 1
        - name: Services
          url: /services/
          weight: 2
        - name: Work
          url: /work/
          weight: 3
        - name: Styleguide
          url: /styleguide/
          weight: 4
          pageRef: styleguide
      footer_secondary:
        - name: Contact
          url: /contact/
          weight: 1
          pageRef: contact
        - name: OpenInfra Korea Event
          url: https://www.openinfradays.kr
          weight: 2
          params:
            external: true
            button: true
      bottom:
        - name: Terms
          url: /terms/
          weight: 1
        - name: Privacy
          url: /privacy/
          weight: 2
  ko:
    weight: 0
    languageName: 한국어
    title: 오픈 인프라 한국 사용자 그룹
    params:
      footer:
        footer_primary_menu_title: 소개
        footer_secondary_menu_title: 참여하기
    menu:
      main:
        - name: Home
          identifier: home
          url: /
          weight: 1
        - name: About
          identifier: about
          #url: /about/
          url: /
          pageRef: about
          weight: 2
        # - name: Branding
        #   parent: services
        #   url: /services/branding
        #   params:
        #     icon: images/icons/icons8-color-palette-100.png
        - name: News
          identifier: news
          url: /news/
          pageRef: news
          weight: 3
        - name: Community
          identifier: community
          url: /community/
          pageRef: community
          weight: 4
        - name: Tech
          identifier: tech
          url: /tech/
          pageRef: tech
          weight: 5
        - name: Get Involved
          identifier: get-involved
          url: /get-involved/
          pageRef: get-involved
          weight: 6
        - name: Hall of Fame
          identifier: hall-of-fame
          url: /hall-of-fame/
          pageRef: hall-of-fame
          weight: 7
        - name: Forum
          url: https://forum.openinfra-kr.org
          weight: 10
          params:
            external: true
            button: true
      footer_primary:
        - name: Team
          url: /team/
          pageRef: team
          weight: 1
        - name: Services
          url: /services/
          weight: 2
        - name: Work
          url: /work/
          weight: 3
        - name: Styleguide
          url: /styleguide/
          weight: 4
          pageRef: styleguide
      footer_secondary:
        - name: Contact
          url: /contact/
          weight: 1
          pageRef: contact
        - name: OpenInfra Korea Event
          url: https://www.openinfradays.kr
          weight: 2
          params:
            external: true
            button: true
      bottom:
        - name: Terms
          url: /terms/
          weight: 1
        - name: Privacy
          url: /privacy/
          weight: 2
permalinks:
  posts: blog/:year/:month/:title/
  pages: :slug/
taxonomies:
  tag: tags
  category: categories
  portfolio: portfolio
  author: authors
markup:
  goldmark:
    renderer:
      unsafe: true
